# Generated by Django 2.2.5 on 2019-10-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(blank=True, max_length=200)),
                ('min_mark', models.IntegerField(default=0)),
                ('max_mark', models.IntegerField(null=True)),
                ('difficulty', models.CharField(choices=[('Very Easy', 'VeryEasy'), ('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Expert', 'Expert')], default='Very Easy', max_length=30)),
                ('question_topic', models.ManyToManyField(to='Questions.Topic')),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Type')),
            ],
        ),
    ]
