# Generated by Django 2.2.5 on 2019-10-02 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_question_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='question_name',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
